server:
  port: 9090

spring:
  application:
    name: consumer-feign-ribbon

feign:
  hystrix:
    enabledï¼štrue

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-8761.com:8761/eureka/
  instance:
    preferIpAddress: true

provider:
  ribbon:
    ServerListRefreshInterval: 15000
    NFLoadBalancerPingClassName: com.javachen.ping.MyPing