server:
  port: 9094

spring:
  application:
    name: rest-consumer-feign-hystrix

feign:
  hystrix:
    enabledï¼štrue


eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-8761.com:8761/eureka/
  instance:
    preferIpAddress: true
