spring:
  application:
    name: provider

server:
  port: 8080

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://eureka-8761.com:8761/eureka/
#  #      defaultZone: http://eureka-8761.com:8761/eureka/,http://eureka-8762.com:8762/eureka/,http://eureka-8763.com:8763/eureka/
#  instance:
#    preferIpAddress: true


management:
  endpoints:
    web:
      exposure:
        # 开放所有监控端点
        include: '*'
  endpoint:
    health:
      # 是否展示健康检查详情
      show-details: always


info:
  app.name: spring-cloud-provider
  company.name: www.javachen.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$